# Generated by Django 4.1.1 on 2022-10-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=40)),
                ('catedra', models.CharField(max_length=40)),
                ('profesor', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('nota', models.IntegerField()),
                ('bibliografia', models.ImageField(null=True, upload_to='materias')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaCalificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('materia', models.CharField(max_length=40)),
                ('catedra', models.CharField(max_length=40)),
                ('profesor', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('puntaje', models.FloatField()),
                ('reseña', models.TextField(max_length=240)),
            ],
        ),
    ]
