# Generated by Django 4.1.1 on 2022-10-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaterias', '0004_estreno_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estreno',
            name='imagen',
            field=models.ImageField(null=True, upload_to='estrenos'),
        ),
    ]
